
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  #config:
    #import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path: /api/v1/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path: /api/v1/order/**

        - id: discovery-server
          uri: http://localhost:8761
          filters:
            SetPath: /
          predicates:
            - Path: /eureka/web
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path: /eureka/**